version: '3.8'
services:
  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory" 
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    environment:
        - DDB_LOCAL_TELEMETRY=0
    ports:
      - "8000:8000"
